[tool.poetry]
name = "university"
version = "1.0.0"
description = ""
authors = ["Tou <51247539+Touexe@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
