from .faculties import Faculties
from .departments import Departments
from .teachers import Teachers
from .teacher_details import TeacherDetails
from .students import Students
from .student_details import StudentDetails
from .student_teachers import StudentTeachers
from .courses import Courses
from .accounts import Accounts